### ISSUE TITLE
As you have explored or written Prometheus SNMP module for OS10? i have tried to use this exporter in OS 10 , but it didn't worked, can you please help me on creating a OS10_promethus_snmp_module or send any document on how to create  customised module

### ISSUE THREAD

**Issue by AMRUTA-BANDHU-CHAUDHURY** [Cryson/idrac_promethus_snmp_module#1]

**Comment by billykwooten** [comment]
I'm not exactly sure what the question is honestly. This snmpd configuration just holds OID values to be walked via the snmpd daemons, specifically in this case the Prometheus snmpd exporter. The OID's in the file are for iDrac monitoring, so i'm quit confused why you're talking about operating systems.

**Comment by billykwooten** [comment]
Please add more verbosity so I can see if something is wrong with the OIDs or if Dell has changed them.

**Comment by AMRUTA-BANDHU-CHAUDHURY** [comment]
No questions is that our dell switches are running OS10 operating system, do you have written any SNM
P prometheus module for getting SNMP details , just i am curious about that, your this module works perfectly for idrac .

**Comment by billykwooten** [comment]
Unfortunately I don't have any OS10/Dell switches to walk OIDs on, the only real help I can give here is to recommend walking all the OID's on your switch and comb through which OIDs you need to monitor. Or ask your Dell enterprise contact for an OID list for your specific switches.
